version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "poc3"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1n6bapg72fuha"
s3_prefix = "poc3"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
